version: "3.3"

services:
  greenlight_db:
    image: postgres
    container_name: greenlight_db
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: ${DB_USERNAME}
        POSTGRES_PASSWORD: ${DB_PASSWORD}
        POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - ${PWD}/pg:/var/lib/postgresql/data
    
  greenlight_pgadmin:
    image: dpage/pgadmin4
    container_name: greenlight_pgadmin
    environment:
      PGADMIN_LISTEN_PORT: 5050
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:5050"
